name: pitoktube
description: PitokTube - Short Video Platform for Pi Network
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State Management
  flutter_riverpod: ^2.6.1

  # Firebase
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0

  # Video
  video_player: ^2.10.0

  # Media
  image_picker: ^1.2.0
  cached_network_image: ^3.4.1

  # Utils
  uuid: ^4.5.1
  intl: ^0.20.2
  share_plus: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/